name: CI

on: [workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

    - run: |
        sudo apt update
        sudo apt install --yes --no-install-recommends \
          python3-pip \
          python3-venv

    - uses: actions/checkout@v3

    - name: pip install
      run: |
        python3 -m venv ~/weewx-venv
        source ~/weewx-venv/bin/activate
        python3 -m pip install weewx
        weectl station create --driver=weewx.drivers.simulator \
          --location=CI \
          --altitude=46,meter \
          --latitude=-27 \
          --longitude=152 \
          --register=n \
          --units=us \
          --no-prompt
        # weectl extension install gw1000

    # - name: Setup tests
    #   run: |
    #     sudo make test-setup-ci

    - name: Launch tests
      run: |

        pwd
        ls -ail /
        ls -ail
        ls -ail ~
        # PYTHONPATH=~/weewx-data/bin python3 -m user.tests.test_egd
        # PYTHONPATH=/home/weewx/bin python3 -m user.tests.test_eg 

#    - name: Archive test-results
#      if: success() || failure()
#      uses: actions/upload-artifact@v3
#      with:
#        name: test-results
#        path: build/test-results
