name: CI

on: [workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

    - run: |
        sudo apt update
        sudo apt install --yes --no-install-recommends \
          python3-pip \
          python3-venv

    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: pip install
      run: |
        python3 -m venv ~/weewx-venv
        source ~/weewx-venv/bin/activate
        python3 -m pip install weewx
        weectl station create --driver=weewx.drivers.simulator \
          --location=CI \
          --altitude=46,meter \
          --latitude=-27 \
          --longitude=152 \
          --register=n \
          --units=us \
          --no-prompt
        weectl extension install ~/work/weewx-gw1000/weewx-gw1000 --yes
        ls -ail ~/work/weewx-gw1000/weewx-gw1000
        mkdir ~/weewx-data/bin/tests
        cp ~/work/weewx-gw1000/weewx-gw1000/tests/test_egd.py ~/weewx-data/bin/tests/
        ls -ail ~/weewx-data/bin/
        ls -ail ~/weewx-data/bin/tests/

    # - name: Setup tests
    #   run: |
    #     sudo make test-setup-ci

    - name: Launch tests
      run: |

        pwd
        # ls -ail /
        # ls -ail
        # ls -ail ~
        # ls -ail ~/work/weewx-gw1000/weewx-gw1000
        # ls -ail ~/weewx-data/bin/user
        PYTHONPATH=~/weewx-data/bin python3 -m user.tests.test_egd 

#    - name: Archive test-results
#      if: success() || failure()
#      uses: actions/upload-artifact@v3
#      with:
#        name: test-results
#        path: build/test-results
